#!/usr/bin/env groovy
pipeline {
    agent any

    stages {
        stage("Checkout the GitHub Repository") {
            steps {
                git branch: "main", url: "https://github.com/DahunsiJ/youverify_DevSecOps.git"
            }
        }
        stage("Terraform Initialization") {
            steps {
                script {
                    dir('devSecOps/aks/terraformIAC') {
                        sh "terraform init"
                    }
                }
            }
        }
        stage("Terraform Format") {
            steps {
                script {
                    dir('devSecOps/aks/terraformIAC') {
                        sh "terraform fmt"
                    }
                }
            }
        }
        stage("Terraform Validate") {
            steps {
                script {
                    dir('devSecOps/aks/terraformIAC') {
                        sh "terraform validate"
                    }
                }
            }
        }
        stage("Terraform Plan") {
            steps {
                script {
                    dir('devSecOps/aks/terraformIAC') {
                        sh "terraform plan"
                    }
                }
            }
        }
        stage("Terraform Apply or Destroy") {
            steps {
                script {
                    def action = 'apply' // or 'destroy' depending on your use case
                    dir('devSecOps/aks/terraformIAC') {
                        sh "terraform ${action} --auto-approve"
                    }
                }
            }
        }
        // stage("Deploy to AKS") {
        //     steps {
        //         script {
        //             dir('kubernetes') {
        //                 sh "aws eks update-kubeconfig --name myapp-eks-cluster"
        //                 sh "kubectl apply -f nginx-deployment.yaml"
        //                 sh "kubectl apply -f nginx-service.yaml"
        //             }
        //         }
        //     }
        // }
    }
}